openapi: 3.0.0
info:
  title: Authentication & Login API
  description: OAuth2, session-based, and JWT token authentication endpoints for user login/logout, provider management, and API access
  version: 1.1.0
  contact:
    name: MCP Gateway Registry
  license:
    name: MIT

servers:
  - url: http://localhost:7860
    description: Local development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: Login
    description: User login endpoints
  - name: Logout
    description: User logout endpoints
  - name: OAuth2
    description: OAuth2 authentication flow
  - name: Providers
    description: Authentication provider information
  - name: Token Generation
    description: JWT token generation endpoints (API access)

paths:
  /api/auth/login:
    get:
      tags:
        - Login
      summary: Get login form
      description: Display login form with available OAuth2 providers
      operationId: getLoginForm
      parameters:
        - name: error
          in: query
          schema:
            type: string
          description: Error message to display
      responses:
        '200':
          description: HTML login form
          content:
            text/html:
              schema:
                type: string

    post:
      tags:
        - Login
      summary: Submit login credentials
      description: Handle login form submission with username and password
      operationId: submitLogin
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  format: password
                  description: Password
      responses:
        '302':
          description: Redirect to home on success or login with error
          headers:
            Set-Cookie:
              schema:
                type: string
                example: mcp_gateway_session=<session_value>; Path=/; HttpOnly; Secure
        '401':
          description: Authentication failed - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/auth/{provider}:
    get:
      tags:
        - OAuth2
      summary: Initiate OAuth2 authentication
      description: Redirect to OAuth2 provider for authentication
      operationId: initiateOAuth2
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum: [keycloak, cognito, oauth2]
          description: OAuth2 provider name
      responses:
        '302':
          description: Redirect to OAuth2 provider authentication endpoint

  /api/auth/auth/callback:
    get:
      tags:
        - OAuth2
      summary: Handle OAuth2 callback
      description: Process OAuth2 provider callback after user authentication
      operationId: handleOAuth2Callback
      parameters:
        - name: error
          in: query
          schema:
            type: string
          description: Error code from provider
        - name: details
          in: query
          schema:
            type: string
          description: Error details
        - name: code
          in: query
          schema:
            type: string
          description: Authorization code from provider
        - name: state
          in: query
          schema:
            type: string
          description: State parameter for CSRF protection
      responses:
        '302':
          description: Redirect to home on success or login with error
          headers:
            Set-Cookie:
              schema:
                type: string
                example: mcp_gateway_session=<session_value>; Path=/; HttpOnly; Secure

  /api/auth/logout:
    get:
      tags:
        - Logout
      summary: Logout via GET
      description: Log out user via GET request (clears session)
      operationId: logoutGet
      responses:
        '302':
          description: Redirect to login page
          headers:
            Set-Cookie:
              schema:
                type: string
                example: mcp_gateway_session=; Path=/; Max-Age=0

    post:
      tags:
        - Logout
      summary: Logout via POST
      description: Log out user via POST request (clears session)
      operationId: logoutPost
      responses:
        '302':
          description: Redirect to login page
          headers:
            Set-Cookie:
              schema:
                type: string
                example: mcp_gateway_session=; Path=/; Max-Age=0

  /api/auth/providers:
    get:
      tags:
        - Providers
      summary: Get available OAuth2 providers
      description: List all configured OAuth2 providers available for authentication
      operationId: getProviders
      responses:
        '200':
          description: List of available providers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvidersResponse'

  /api/auth/me:
    get:
      tags:
        - Login
      summary: Get current user information
      description: Get authentication and user details for current authenticated session
      operationId: getCurrentUser
      security:
        - SessionCookie: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/token:
    post:
      tags:
        - Token Generation
      summary: Get JWT token using username and password
      description: Generate JWT token directly using username and password credentials (OAuth2 Resource Owner Password Credentials flow). Intended for CLI tools, scripts, and external services that need API access without browser login.
      operationId: getTokenDirect
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  format: password
                  description: Password
                grant_type:
                  type: string
                  enum: [password]
                  default: password
                  description: OAuth2 grant type (must be password)
                requested_scopes:
                  type: array
                  items:
                    type: string
                  description: Optional list of requested scopes (e.g., [publish_agent, modify_service])
                expires_in_hours:
                  type: integer
                  minimum: 1
                  maximum: 24
                  default: 8
                  description: Token expiration time in hours
      responses:
        '200':
          description: JWT token successfully generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication failed - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Token generation server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/m2m:
    post:
      tags:
        - Token Generation
      summary: Get JWT token using client credentials (Machine-to-Machine)
      description: Generate JWT token for service-to-service authentication using client credentials (OAuth2 Client Credentials flow). Intended for automated services, CI/CD pipelines, and inter-service communication.
      operationId: getM2MToken
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - client_id
                - client_secret
              properties:
                client_id:
                  type: string
                  description: Keycloak client ID (e.g., mcp-gateway-m2m or agent-{name}-m2m)
                client_secret:
                  type: string
                  format: password
                  description: Keycloak client secret
                grant_type:
                  type: string
                  enum: [client_credentials]
                  default: client_credentials
                  description: OAuth2 grant type (must be client_credentials)
                requested_scopes:
                  type: array
                  items:
                    type: string
                  description: Optional list of requested scopes (e.g., [publish_agent, modify_service])
                expires_in_hours:
                  type: integer
                  minimum: 1
                  maximum: 24
                  default: 24
                  description: Token expiration time in hours (longer default for M2M)
      responses:
        '200':
          description: JWT token successfully generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/M2MTokenResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication failed - invalid client credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Token generation server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    SessionCookie:
      type: apiKey
      in: cookie
      name: mcp_gateway_session
      description: Session cookie set after successful login

  schemas:
    ProvidersResponse:
      type: object
      required:
        - providers
      properties:
        providers:
          type: array
          items:
            $ref: '#/components/schemas/Provider'

    Provider:
      type: object
      required:
        - name
        - display_name
      properties:
        name:
          type: string
          description: Provider identifier (e.g., keycloak)
        display_name:
          type: string
          description: Display name for UI
        icon:
          type: string
          description: Icon identifier
        description:
          type: string
          description: Provider description
        authorization_endpoint:
          type: string
          format: uri
          description: OAuth2 authorization endpoint
        config:
          type: object
          description: Provider-specific configuration

    UserInfo:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          description: Username
        email:
          type: string
          format: email
          description: User email
        auth_method:
          type: string
          enum: [oauth2, form, basic]
          description: Authentication method used
        provider:
          type: string
          description: OAuth2 provider name
        scopes:
          type: array
          items:
            type: string
          description: User's assigned scopes/permissions
        groups:
          type: array
          items:
            type: string
          description: User's group memberships
        is_admin:
          type: boolean
          description: Whether user is an administrator
        attributes:
          type: object
          description: Additional user attributes
          additionalProperties:
            type: string

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Human-readable error message
        error_code:
          type: string
          description: Optional error code
        request_id:
          type: string
          description: Unique request identifier

    TokenResponse:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
          description: JWT access token for API authentication
        refresh_token:
          type: string
          description: Refresh token to get new access token when expired
        expires_in:
          type: integer
          description: Token expiration time in seconds
        token_type:
          type: string
          enum: [Bearer]
          description: Token type (always Bearer)
        scope:
          type: string
          description: Space-separated list of granted scopes
        requested_scopes:
          type: array
          items:
            type: string
          description: List of requested scopes that were granted

    M2MTokenResponse:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
          description: JWT access token for service-to-service authentication
        expires_in:
          type: integer
          description: Token expiration time in seconds
        token_type:
          type: string
          enum: [Bearer]
          description: Token type (always Bearer)
        scope:
          type: string
          description: Space-separated list of granted scopes
        requested_scopes:
          type: array
          items:
            type: string
          description: List of requested scopes that were granted
